### ISSUE TITLE
XML node and values coloring

### ISSUE THREAD

**Issue by lavanyakomarasamy** [mcous/xmlovely#2]
Hi Mike Cousins,

I am looking for the library, which will format xml with coloring like tag should have one color and values should have one color.
Is it possible? Please help me to fix this.

**Comment by mcous** [comment]
Hi! I'm not sure I understand your question is, so I'm sorry if I'm wrong, but it sounds like you're looking for some sort of tool to help with XML syntax highlighting. This library is purely text-based and only deals with whitespace, so I don't think it's what you're looking for.

**Comment by lavanyakomarasamy** [comment]
Exactly Mike Cousins, thank you so much for your response.
